interface RecipeDetails {
    vegetarian: boolean;
    vegan: boolean;
    glutenFree: boolean;
    dairyFree: boolean;
    veryHealthy: boolean;
    cheap: boolean;
    veryPopular: boolean;
    sustainable: boolean;
    lowFodmap: boolean;
    weightWatcherSmartPoints: number;
    gaps: string;
    preparationMinutes: number;
    cookingMinutes: number;
    aggregateLikes: number;
    healthScore: number;
    creditsText: string;
    license?: string;
    sourceName: string;
    pricePerServing: number;
    extendedIngredients: any[];
    id: number;
    title: string;
    readyInMinutes: number;
    servings: number;
    sourceUrl: string;
    image: string;
    imageType: string;
    summary: string;
    cuisines: string[];
    dishTypes: string[];
    diets: string[];
    occasions: string[];
    winePairing: object;
    instructions: string;
    analyzedInstructions: Instruction[];
    report: string | null;
    tips: any;
    openLicense: number;
    suspiciousDataScore: number;
    approved: number;
    unknownIngredients: any[];
    userTags: string[];
    originalId: number | null;
    spoonacularSourceUrl: string;
}