name: Heroku Deployment

on:
  push:
    branches: 
        - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Use Node.js 18.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.x
      # - run: npm ci
      # - run: npm run build

      - name: Set up Python3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install ruff pytest
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
        - uses: actions/checkout@v3

        - uses: akhileshns/heroku-deploy@v3.12.14
          with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "drp23"
                heroku_email: "tangboxuan1999@gmail.com"