name: Heroku Deployment

on:
  push:
    branches: 
        - main
        - automatically-build-app

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      # - name: Use Node.js 18.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.x
      # - run: npm ci
      # - run: npm run build

      - name: Set up Python3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest backend/test.py --doctest-modules --junitxml=junit/test-results.xml --cov=backend --cov-report=xml --cov-report=html

      - name: Display pytest test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: junit/test-results.xml

      - uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: android
        
        if: always()
  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
        - uses: actions/checkout@v3

        - uses: akhileshns/heroku-deploy@v3.12.14
          with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "drp23"
                heroku_email: "tangboxuan1999@gmail.com"